### ISSUE TITLE
Client is module and cannot be called

### ISSUE THREAD

**Issue by kevwilhelm95** [jaythequant/kucoin-cli#1]
I am trying to define a function that sets the client. (See code block 1 - and I have replaced the values with my API keys)

`def KC_SetClient():
    api_key = "api_key"
    api_secret = "api_secret"
    api_passphrase = "api_passphrase"
    client = Client(api_key, api_secret, api_passphrase)
    return client`

However, I get an error that returns the following: 
`Traceback (most recent call last):
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/hw/0w064hss2mv96tfz78bybyrc0000gn/T/ipykernel_47018/1779709503.py", line 7, in <cell line: 7>
    client = Client(api_key, api_secret, api_passphrase)
TypeError: 'module' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/executing/executing.py", line 312, in executing
    args = executing_cache[key]
KeyError: (<code object run_code at 0x7f8c98500df0, file "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3362>, 140241827532272, 74)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1993, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/IPython/core/ultratb.py", line 799, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/IPython/core/ultratb.py", line 854, in get_records
    return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/stack_data/core.py", line 563, in stack_data
    yield from collapse_repeated(
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/stack_data/utils.py", line 84, in collapse_repeated
    yield from map(mapper, original_group)
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/stack_data/core.py", line 553, in mapper
    return cls(f, options)
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/stack_data/core.py", line 518, in __init__
    self.executing = Source.executing(frame_or_tb)
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/executing/executing.py", line 364, in executing
    args = find(source=cls.for_frame(frame), retry_cache=True)
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/executing/executing.py", line 247, in for_frame
    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/executing/executing.py", line 265, in for_filename
    result = source_cache[filename] = cls._for_filename_and_lines(filename, lines)
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/executing/executing.py", line 276, in _for_filename_and_lines
    result = source_cache[(filename, lines)] = cls(filename, lines)
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/stack_data/core.py", line 81, in __init__
    self.asttokens()
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/executing/executing.py", line 408, in asttokens
    return ASTTokens(
  File "/Users/Kevin/opt/anaconda3/envs/algo_trader/lib/python3.8/site-packages/asttokens/asttokens.py", line 61, in __init__
    source_text = six.ensure_text(source_text)
AttributeError: module 'six' has no attribute 'ensure_text'
`

I am running in an environment that is Python 3.8.12

**Comment by jaythequant** [comment]
Hey Kev, 

I copied the code block provided and got it formatted per line (I believe it unformatted in your post) + added what I assume is the surround code:

```
from kucoincli.client import Client

def KC_SetClient(): 
    api_key = "api_key" 
    api_secret = "api_secret" 
    api_passphrase = "api_passphrase" 
    client = Client(api_key, api_secret, api_passphrase) 
    return client

client = KC_SetClient()

print(client.symbols())
```

This function does seem to run fine for me. I have a feeling the issue either has to do with the import statement or the calling of the function part of your code, rather than the function itself. If you could post a full block of what you have, I can troubleshoot a bit better. Maybe try copy pasting the block above and see if that runs. As an aside, this function seems a bit odd. You could just run the `client = Client(api_key, api_secret, api_passphrase)` line and not have any need to define the function.

**Comment by kevwilhelm95** [comment]
My import statement is `import kucoincli.client as Client`. You are correct using `from kucoincli.client import Client` but the documentation states `import kucoincli.client as Client`. Just wanted to point that out to you. Thank you!

**Comment by jaythequant** [comment]
Oh I see, that definitely should say from! I'll update that line in the docs ASAP. Thank you. When importing you will need to use the from line.
